import type { LessonContent } from "./types";

/** Study sheets for the A1 lessons, keyed by lesson id (see lib/curriculum.ts). */
export const A1_CONTENT: Record<string, LessonContent> = {
  // Introduce yourself
  "a1-01-introduce-yourself": {
    goals: [
      "Say your name and where you come from",
      "Tell people where you live and what you do",
      "Ask others the same questions with Wie, Woher, Wo and Was",
    ],
    vocab: [
      { de: "Name", en: "name", gender: "m", plural: "Namen" },
      { de: "Land", en: "country", gender: "n", plural: "Länder" },
      { de: "Stadt", en: "city, town", gender: "f", plural: "Städte" },
      { de: "Beruf", en: "profession, job", gender: "m", plural: "Berufe" },
      { de: "Student", en: "student (male)", gender: "m", plural: "Studenten" },
      { de: "Ingenieur", en: "engineer (male)", gender: "m", plural: "Ingenieure" },
      { de: "heißen", en: "to be called" },
      { de: "kommen", en: "to come" },
      { de: "wohnen", en: "to live (reside)" },
      { de: "arbeiten", en: "to work" },
      { de: "sprechen", en: "to speak" },
    ],
    phrases: [
      { de: "Ich «heiße» Anna.", en: "My name is Anna." },
      { de: "Ich «komme aus» Indien.", en: "I come from India." },
      { de: "Ich «wohne in» Berlin.", en: "I live in Berlin." },
      { de: "Ich «bin» Student und komme aus Spanien.", en: "I am a student and I come from Spain." },
      { de: "«Wie heißen Sie?»", en: "What is your name? (formal)" },
      { de: "«Was machst du beruflich?»", en: "What do you do for a living?" },
    ],
    grammarIds: ["gr-a1-02-sein-haben", "gr-a1-08-questions"],
    dialogue: [
      { speaker: "Anna", de: "Hallo! Ich heiße Anna. Wie heißt du?", en: "Hello! My name is Anna. What's your name?" },
      { speaker: "Ravi", de: "Hallo Anna! Ich heiße Ravi.", en: "Hello Anna! My name is Ravi." },
      { speaker: "Anna", de: "Woher kommst du, Ravi?", en: "Where do you come from, Ravi?" },
      { speaker: "Ravi", de: "Ich komme aus Indien. Und du?", en: "I come from India. And you?" },
      { speaker: "Anna", de: "Ich komme aus Hamburg, aber ich wohne in Berlin.", en: "I come from Hamburg, but I live in Berlin." },
      { speaker: "Ravi", de: "Was machst du beruflich?", en: "What do you do for a living?" },
      { speaker: "Anna", de: "Ich bin Ingenieurin. Und du?", en: "I am an engineer. And you?" },
      { speaker: "Ravi", de: "Ich bin Student. Ich wohne jetzt in München.", en: "I am a student. I live in Munich now." },
    ],
    check: [
      { prompt: "Ich ___ Ingenieur.", answer: "bin", hint: "Which form of sein goes with ich?" },
      { prompt: "Er ___ Peter.", answer: "heißt", accept: ["ist"], hint: "With er, sie and es the verb ending is -t." },
      { prompt: "___ kommst du? – Aus Polen.", answer: "Woher", hint: "Which question word asks about origin?" },
    ],
  },

  // Family
  "a1-02-family": {
    goals: [
      "Name the members of your family",
      "Say how many siblings or children you have",
      "Give and ask for a person's age",
    ],
    vocab: [
      { de: "Familie", en: "family", gender: "f", plural: "Familien" },
      { de: "Mutter", en: "mother", gender: "f", plural: "Mütter" },
      { de: "Vater", en: "father", gender: "m", plural: "Väter" },
      { de: "Bruder", en: "brother", gender: "m", plural: "Brüder" },
      { de: "Schwester", en: "sister", gender: "f", plural: "Schwestern" },
      { de: "Kind", en: "child", gender: "n", plural: "Kinder" },
      { de: "Sohn", en: "son", gender: "m", plural: "Söhne" },
      { de: "Tochter", en: "daughter", gender: "f", plural: "Töchter" },
      { de: "Großmutter", en: "grandmother", gender: "f", plural: "Großmütter" },
      { de: "Großvater", en: "grandfather", gender: "m", plural: "Großväter" },
      { de: "haben", en: "to have" },
      { de: "alt", en: "old" },
    ],
    phrases: [
      { de: "Ich «habe» zwei Brüder.", en: "I have two brothers." },
      { de: "«Mein» Vater heißt Thomas.", en: "My father is called Thomas." },
      { de: "«Meine» Schwester wohnt in Wien.", en: "My sister lives in Vienna." },
      { de: "«Wie alt ist» deine Mutter?", en: "How old is your mother?" },
      { de: "Mein Bruder ist «dreißig Jahre alt».", en: "My brother is thirty years old." },
      { de: "«Hast du» Geschwister?", en: "Do you have siblings?" },
    ],
    grammarIds: ["gr-a1-10-possessives", "gr-a1-02-sein-haben"],
    dialogue: [
      { speaker: "Lena", de: "Hast du Geschwister, Tom?", en: "Do you have siblings, Tom?" },
      { speaker: "Tom", de: "Ja, ich habe eine Schwester.", en: "Yes, I have a sister." },
      { speaker: "Lena", de: "Wie heißt deine Schwester?", en: "What is your sister called?" },
      { speaker: "Tom", de: "Meine Schwester heißt Clara. Sie ist zwanzig Jahre alt.", en: "My sister is called Clara. She is twenty years old." },
      { speaker: "Lena", de: "Wohnt sie auch in Leipzig?", en: "Does she also live in Leipzig?" },
      { speaker: "Tom", de: "Nein, sie wohnt in Wien. Und du? Hast du Geschwister?", en: "No, she lives in Vienna. And you? Do you have siblings?" },
      { speaker: "Lena", de: "Ja, ich habe zwei Brüder. Mein Bruder Paul ist schon vierzig.", en: "Yes, I have two brothers. My brother Paul is already forty." },
    ],
    check: [
      { prompt: "Ich ___ eine Schwester.", answer: "habe", hint: "Present tense of the verb for possession, ich-form." },
      { prompt: "Hast du eine Schwester? – Ja, ___ Schwester heißt Eva.", answer: "meine", hint: "Possessive for ich; the noun is feminine, so add -e." },
      { prompt: "Mein Bruder ___ zwanzig Jahre alt.", answer: "ist", hint: "Age uses the verb sein, third person singular." },
    ],
  },

  // Numbers, time & dates
  "a1-03-numbers-time-dates": {
    goals: [
      "Tell and ask the time",
      "Name weekdays and months and say when something happens",
      "Say and ask when your birthday is",
    ],
    vocab: [
      { de: "Uhr", en: "clock, o'clock", gender: "f", plural: "Uhren" },
      { de: "Stunde", en: "hour", gender: "f", plural: "Stunden" },
      { de: "Minute", en: "minute", gender: "f", plural: "Minuten" },
      { de: "Tag", en: "day", gender: "m", plural: "Tage" },
      { de: "Woche", en: "week", gender: "f", plural: "Wochen" },
      { de: "Monat", en: "month", gender: "m", plural: "Monate" },
      { de: "Jahr", en: "year", gender: "n", plural: "Jahre" },
      { de: "Geburtstag", en: "birthday", gender: "m", plural: "Geburtstage" },
      { de: "Wochenende", en: "weekend", gender: "n", plural: "Wochenenden" },
      { de: "heute", en: "today" },
      { de: "morgen", en: "tomorrow" },
      { de: "halb", en: "half" },
    ],
    phrases: [
      { de: "«Wie spät ist es?»", en: "What time is it?" },
      { de: "Es ist «halb acht».", en: "It is half past seven." },
      { de: "Der Kurs beginnt «um neun Uhr».", en: "The course starts at nine o'clock." },
      { de: "Ich habe «am Montag» frei.", en: "I am off on Monday." },
      { de: "Mein Geburtstag ist «im Mai».", en: "My birthday is in May." },
      { de: "«Wann hast du Geburtstag?»", en: "When is your birthday?" },
    ],
    grammarIds: ["gr-a2-04-prepositions", "gr-a1-08-questions"],
    dialogue: [
      { speaker: "Julia", de: "Entschuldigung, wie spät ist es?", en: "Excuse me, what time is it?" },
      { speaker: "Max", de: "Es ist Viertel nach zehn.", en: "It is a quarter past ten." },
      { speaker: "Julia", de: "Danke! Wann beginnt der Deutschkurs?", en: "Thanks! When does the German course start?" },
      { speaker: "Max", de: "Er beginnt um elf Uhr.", en: "It starts at eleven o'clock." },
      { speaker: "Julia", de: "Haben wir am Freitag auch Kurs?", en: "Do we have class on Friday too?" },
      { speaker: "Max", de: "Nein, am Freitag haben wir frei.", en: "No, we are off on Friday." },
      { speaker: "Julia", de: "Super! Wann hast du Geburtstag, Max?", en: "Great! When is your birthday, Max?" },
      { speaker: "Max", de: "Ich habe im Juli Geburtstag. Und du?", en: "My birthday is in July. And you?" },
    ],
    check: [
      { prompt: "Der Film beginnt ___ acht Uhr.", answer: "um", hint: "Clock times use one fixed preposition: 'at ... o'clock'." },
      { prompt: "Ich habe ___ Montag Unterricht.", answer: "am", hint: "Days of the week take the contracted 'on the'." },
      { prompt: "Mein Geburtstag ist ___ Dezember.", answer: "im", hint: "Months take the contracted 'in the'." },
    ],
  },

  // Food & drinks (ordering)
  "a1-04-food-and-drinks": {
    goals: [
      "Order food and drinks politely",
      "Say what you would like with möchten",
      "Ask for the bill and pay",
    ],
    vocab: [
      { de: "Kaffee", en: "coffee", gender: "m" },
      { de: "Wasser", en: "water", gender: "n" },
      { de: "Brot", en: "bread", gender: "n", plural: "Brote" },
      { de: "Apfel", en: "apple", gender: "m", plural: "Äpfel" },
      { de: "Suppe", en: "soup", gender: "f", plural: "Suppen" },
      { de: "Salat", en: "salad", gender: "m", plural: "Salate" },
      { de: "Speisekarte", en: "menu", gender: "f", plural: "Speisekarten" },
      { de: "Rechnung", en: "bill", gender: "f", plural: "Rechnungen" },
      { de: "möchten", en: "would like to" },
      { de: "nehmen", en: "to take" },
      { de: "bezahlen", en: "to pay" },
      { de: "trinken", en: "to drink" },
    ],
    phrases: [
      { de: "Ich «möchte» einen Kaffee, bitte.", en: "I would like a coffee, please." },
      { de: "«Ich nehme» die Suppe.", en: "I'll have the soup." },
      { de: "Was «möchten Sie» trinken?", en: "What would you like to drink?" },
      { de: "«Ich möchte bezahlen», bitte.", en: "I would like to pay, please." },
      { de: "Haben Sie «einen Tisch» für zwei Personen?", en: "Do you have a table for two people?" },
      { de: "«Das schmeckt» sehr gut.", en: "This tastes very good." },
    ],
    grammarIds: ["gr-a2-07-modal-verbs", "gr-a1-06-accusative"],
    dialogue: [
      { speaker: "Tim", de: "Guten Tag! Was möchten Sie trinken?", en: "Good day! What would you like to drink?" },
      { speaker: "Sara", de: "Ich möchte einen Kaffee, bitte.", en: "I would like a coffee, please." },
      { speaker: "Tim", de: "Gern. Und zu essen?", en: "Gladly. And something to eat?" },
      { speaker: "Sara", de: "Ich nehme die Suppe und ein Brot.", en: "I'll have the soup and a piece of bread." },
      { speaker: "Tim", de: "Sehr gut. Möchten Sie auch Wasser?", en: "Very good. Would you like water too?" },
      { speaker: "Sara", de: "Ja, ein Wasser, bitte.", en: "Yes, a water, please." },
      { speaker: "Tim", de: "Kommt sofort.", en: "Coming right up." },
      { speaker: "Sara", de: "Danke schön!", en: "Thank you very much!" },
    ],
    check: [
      { prompt: "Ich möchte ___ Kaffee, bitte.", answer: "einen", hint: "Kaffee is masculine; the accusative adds -en to the article." },
      { prompt: "Was ___ Sie trinken?", answer: "möchten", accept: ["wollen"], hint: "Polite modal verb meaning 'would like', conjugated for Sie." },
      { prompt: "Ich nehme ___ Salat und ein Brot.", answer: "einen", accept: ["den"], hint: "Salat is masculine; the accusative adds -en to the article." },
    ],
  },

  // Daily routine
  "a1-05-daily-routine": {
    goals: [
      "Describe your day from morning to evening",
      "Use separable verbs such as aufstehen and einkaufen",
      "Say when you do things with times at the start of the sentence",
    ],
    vocab: [
      { de: "aufstehen", en: "to get up" },
      { de: "frühstücken", en: "to have breakfast" },
      { de: "duschen", en: "to shower" },
      { de: "arbeiten", en: "to work" },
      { de: "einkaufen", en: "to go shopping" },
      { de: "kochen", en: "to cook" },
      { de: "fernsehen", en: "to watch TV" },
      { de: "schlafen", en: "to sleep" },
      { de: "Morgen", en: "morning", gender: "m", plural: "Morgen" },
      { de: "Abend", en: "evening", gender: "m", plural: "Abende" },
      { de: "Mittagessen", en: "lunch", gender: "n", plural: "Mittagessen" },
      { de: "Feierabend", en: "end of the working day", gender: "m" },
    ],
    phrases: [
      { de: "Ich «stehe um sieben Uhr auf».", en: "I get up at seven o'clock." },
      { de: "Um acht Uhr «frühstücke ich».", en: "At eight o'clock I have breakfast." },
      { de: "Dann «fahre ich» zur Arbeit.", en: "Then I go to work." },
      { de: "Am Abend «sehe ich fern».", en: "In the evening I watch TV." },
      { de: "Am Samstag «kaufe ich» im Supermarkt «ein».", en: "On Saturday I go shopping at the supermarket." },
      { de: "Um elf Uhr «gehe ich schlafen».", en: "At eleven o'clock I go to sleep." },
    ],
    grammarIds: ["gr-a2-08-separable-verbs", "gr-a1-07-verb-second"],
    dialogue: [
      { speaker: "Nina", de: "Wann stehst du morgens auf, Jonas?", en: "When do you get up in the morning, Jonas?" },
      { speaker: "Jonas", de: "Ich stehe um sechs Uhr auf.", en: "I get up at six o'clock." },
      { speaker: "Nina", de: "So früh! Und was machst du dann?", en: "So early! And what do you do then?" },
      { speaker: "Jonas", de: "Zuerst dusche ich, dann frühstücke ich.", en: "First I shower, then I have breakfast." },
      { speaker: "Nina", de: "Wann beginnt deine Arbeit?", en: "When does your work start?" },
      { speaker: "Jonas", de: "Um acht Uhr. Um fünf habe ich Feierabend.", en: "At eight o'clock. At five I finish for the day." },
      { speaker: "Nina", de: "Und am Abend?", en: "And in the evening?" },
      { speaker: "Jonas", de: "Dann koche ich und sehe fern. Um elf gehe ich schlafen.", en: "Then I cook and watch TV. At eleven I go to sleep." },
    ],
    check: [
      { prompt: "Ich ___ um sieben Uhr auf.", answer: "stehe", hint: "The conjugated verb stays in second position; the ich-form ends in -e." },
      { prompt: "Am Abend ___ ich fern.", answer: "sehe", accept: ["schaue"], hint: "The verb comes right after the time phrase; the prefix goes to the end." },
      { prompt: "Am Samstag kaufe ich im Supermarkt ___.", answer: "ein", hint: "The separable prefix goes to the end of the clause." },
    ],
  },

  // Shopping
  "a1-06-shopping": {
    goals: [
      "Ask for the price of things",
      "Say what you need and what you are looking for",
      "Name amounts such as a kilo or a bottle",
    ],
    vocab: [
      { de: "Supermarkt", en: "supermarket", gender: "m", plural: "Supermärkte" },
      { de: "Preis", en: "price", gender: "m", plural: "Preise" },
      { de: "Euro", en: "euro", gender: "m", plural: "Euro" },
      { de: "Kilo", en: "kilo", gender: "n", plural: "Kilos" },
      { de: "Flasche", en: "bottle", gender: "f", plural: "Flaschen" },
      { de: "Tüte", en: "bag", gender: "f", plural: "Tüten" },
      { de: "Milch", en: "milk", gender: "f" },
      { de: "Jacke", en: "jacket", gender: "f", plural: "Jacken" },
      { de: "Pullover", en: "sweater", gender: "m", plural: "Pullover" },
      { de: "kaufen", en: "to buy" },
      { de: "brauchen", en: "to need" },
      { de: "kosten", en: "to cost" },
    ],
    phrases: [
      { de: "«Was kostet» das Brot?", en: "How much is the bread?" },
      { de: "«Wie viel kosten» die Äpfel?", en: "How much are the apples?" },
      { de: "Ich «brauche» eine Flasche Milch.", en: "I need a bottle of milk." },
      { de: "Ich «möchte» ein Kilo Äpfel.", en: "I would like a kilo of apples." },
      { de: "Ich «suche» eine Jacke.", en: "I am looking for a jacket." },
      { de: "«Das ist alles», danke.", en: "That's all, thank you." },
    ],
    grammarIds: ["gr-a1-06-accusative", "gr-a1-04-articles"],
    dialogue: [
      { speaker: "Paul", de: "Guten Tag! Was brauchen Sie?", en: "Good day! What do you need?" },
      { speaker: "Eva", de: "Ich brauche eine Flasche Milch und ein Brot.", en: "I need a bottle of milk and a loaf of bread." },
      { speaker: "Paul", de: "Gern. Sonst noch etwas?", en: "Gladly. Anything else?" },
      { speaker: "Eva", de: "Ja, ich möchte Äpfel. Was kostet das Kilo?", en: "Yes, I would like apples. How much is a kilo?" },
      { speaker: "Paul", de: "Zwei Euro fünfzig.", en: "Two euros fifty." },
      { speaker: "Eva", de: "Gut, dann nehme ich zwei Kilo.", en: "Good, then I'll take two kilos." },
      { speaker: "Paul", de: "Das macht zusammen neun Euro.", en: "That comes to nine euros altogether." },
      { speaker: "Eva", de: "Hier, bitte. Danke und tschüss!", en: "Here you are. Thanks and bye!" },
    ],
    check: [
      { prompt: "Ich brauche ___ Flasche Milch.", answer: "eine", hint: "Flasche is feminine; the indefinite article takes an -e." },
      { prompt: "Was ___ die Jacke?", answer: "kostet", hint: "The subject is singular, so the verb ends in -t." },
      { prompt: "Ich brauche ___ Pullover und eine Jacke.", answer: "einen", hint: "Pullover is masculine; the accusative adds -en to the article." },
    ],
  },

  // Directions & places in town
  "a1-07-directions-and-places": {
    goals: [
      "Ask where a place is and how to get there",
      "Understand and give simple directions",
      "Say where something is with neben and gegenüber",
    ],
    vocab: [
      { de: "Bahnhof", en: "train station", gender: "m", plural: "Bahnhöfe" },
      { de: "Apotheke", en: "pharmacy", gender: "f", plural: "Apotheken" },
      { de: "Post", en: "post office", gender: "f" },
      { de: "Straße", en: "street", gender: "f", plural: "Straßen" },
      { de: "Ecke", en: "corner", gender: "f", plural: "Ecken" },
      { de: "Ampel", en: "traffic light", gender: "f", plural: "Ampeln" },
      { de: "geradeaus", en: "straight ahead" },
      { de: "links", en: "left" },
      { de: "rechts", en: "right" },
      { de: "abbiegen", en: "to turn" },
      { de: "gegenüber", en: "opposite" },
      { de: "neben", en: "next to" },
    ],
    phrases: [
      { de: "Entschuldigung, «wo ist» der Bahnhof?", en: "Excuse me, where is the train station?" },
      { de: "«Wie komme ich zum» Bahnhof?", en: "How do I get to the train station?" },
      { de: "«Gehen Sie geradeaus.»", en: "Go straight ahead." },
      { de: "«Biegen Sie links ab.»", en: "Turn left." },
      { de: "Die Apotheke ist «neben der» Post.", en: "The pharmacy is next to the post office." },
      { de: "Der Supermarkt ist «gegenüber dem» Bahnhof.", en: "The supermarket is opposite the train station." },
    ],
    grammarIds: ["gr-a2-03-dative", "gr-a2-09-imperative"],
    dialogue: [
      { speaker: "Daniel", de: "Entschuldigung, wie komme ich zur Post?", en: "Excuse me, how do I get to the post office?" },
      { speaker: "Sophie", de: "Gehen Sie hier geradeaus bis zur Ampel.", en: "Go straight ahead here to the traffic light." },
      { speaker: "Daniel", de: "Und dann?", en: "And then?" },
      { speaker: "Sophie", de: "Dort biegen Sie links ab. Die Post ist neben der Apotheke.", en: "There you turn left. The post office is next to the pharmacy." },
      { speaker: "Daniel", de: "Ist das weit?", en: "Is it far?" },
      { speaker: "Sophie", de: "Nein, nur fünf Minuten zu Fuß.", en: "No, only five minutes on foot." },
      { speaker: "Daniel", de: "Vielen Dank!", en: "Thank you very much!" },
      { speaker: "Sophie", de: "Gern geschehen!", en: "You're welcome!" },
    ],
    check: [
      { prompt: "Wie komme ich ___ Bahnhof?", answer: "zum", hint: "Zu plus a masculine noun contracts into one word." },
      { prompt: "Die Apotheke ist neben ___ Post.", answer: "der", hint: "Dative after this preposition; Post is feminine." },
      { prompt: "Biegen Sie an der Ampel links ___.", answer: "ab", hint: "The verb prefix is detached and moves to the end of the clause." },
    ],
  },

  // Hobbies & free time
  "a1-08-hobbies": {
    goals: [
      "Say what you like doing with gern",
      "Say what you can do with können",
      "Tell how often you do something",
    ],
    vocab: [
      { de: "Hobby", en: "hobby", gender: "n", plural: "Hobbys" },
      { de: "Freizeit", en: "free time", gender: "f" },
      { de: "Musik", en: "music", gender: "f" },
      { de: "Buch", en: "book", gender: "n", plural: "Bücher" },
      { de: "Freund", en: "friend (male)", gender: "m", plural: "Freunde" },
      { de: "Fußball", en: "football, soccer", gender: "m" },
      { de: "schwimmen", en: "to swim" },
      { de: "lesen", en: "to read" },
      { de: "spielen", en: "to play" },
      { de: "können", en: "can, to be able to" },
      { de: "oft", en: "often" },
      { de: "manchmal", en: "sometimes" },
    ],
    phrases: [
      { de: "Ich «spiele gern» Fußball.", en: "I like playing football." },
      { de: "Ich «schwimme nicht gern».", en: "I don't like swimming." },
      { de: "«Was machst du» in deiner Freizeit?", en: "What do you do in your free time?" },
      { de: "Ich «kann» gut kochen.", en: "I can cook well." },
      { de: "Ich höre «manchmal» Musik.", en: "I sometimes listen to music." },
      { de: "Am Wochenende «treffe ich oft» Freunde.", en: "At the weekend I often meet friends." },
    ],
    grammarIds: ["gr-a2-07-modal-verbs", "gr-a1-09-negation"],
    dialogue: [
      { speaker: "Mia", de: "Was machst du in deiner Freizeit, Felix?", en: "What do you do in your free time, Felix?" },
      { speaker: "Felix", de: "Ich spiele gern Fußball. Und du?", en: "I like playing football. And you?" },
      { speaker: "Mia", de: "Ich lese gern, aber ich schwimme auch oft.", en: "I like reading, but I also swim often." },
      { speaker: "Felix", de: "Schwimmen kann ich nicht so gut.", en: "I can't swim that well." },
      { speaker: "Mia", de: "Wir können zusammen schwimmen gehen!", en: "We can go swimming together!" },
      { speaker: "Felix", de: "Gern! Hast du am Wochenende Zeit?", en: "Gladly! Do you have time at the weekend?" },
      { speaker: "Mia", de: "Ja, am Samstag habe ich Zeit.", en: "Yes, on Saturday I have time." },
      { speaker: "Felix", de: "Super, bis Samstag!", en: "Great, see you Saturday!" },
    ],
    check: [
      { prompt: "Ich spiele ___ Fußball.", answer: "gern", accept: ["gerne", "oft"], hint: "Which adverb says you like doing something?" },
      { prompt: "Er ___ gut kochen.", answer: "kann", hint: "With er, sie and es this modal verb has no ending." },
      { prompt: "Ich schwimme ___ gern, das Wasser ist zu kalt.", answer: "nicht", hint: "To say you dislike something, put the negation before 'gern'." },
    ],
  },
};
