import type { LessonContent } from "./types";

/** Study sheets for the A2 lessons, keyed by lesson id (see lib/curriculum.ts). */
export const A2_CONTENT: Record<string, LessonContent> = {
  // My last weekend
  "a2-01-last-weekend": {
    goals: [
      "Tell what you did last weekend in the Perfekt",
      "Choose between haben and sein for the past",
      "Place the participle at the end of the sentence",
    ],
    vocab: [
      { de: "Wochenende", en: "weekend", gender: "n", plural: "Wochenenden" },
      { de: "Ausflug", en: "trip, outing", gender: "m", plural: "Ausflüge" },
      { de: "Film", en: "film, movie", gender: "m", plural: "Filme" },
      { de: "Freund", en: "friend", gender: "m", plural: "Freunde" },
      { de: "treffen", en: "to meet" },
      { de: "besuchen", en: "to visit" },
      { de: "einkaufen", en: "to go shopping" },
      { de: "gehen", en: "to go (on foot)" },
      { de: "fahren", en: "to go (by vehicle), to drive" },
      { de: "sehen", en: "to see, to watch" },
      { de: "schlafen", en: "to sleep" },
      { de: "kochen", en: "to cook" },
    ],
    phrases: [
      { de: "Am Samstag «habe ich Freunde getroffen».", en: "On Saturday I met friends." },
      { de: "Am Sonntag «bin ich spazieren gegangen».", en: "On Sunday I went for a walk." },
      { de: "Wir «haben einen Film gesehen».", en: "We watched a film." },
      { de: "«Ich bin nach Hamburg gefahren» und habe meine Schwester besucht.", en: "I went to Hamburg and visited my sister." },
      { de: "Am Abend «haben wir zusammen gekocht».", en: "In the evening we cooked together." },
      { de: "Ich «habe lange geschlafen».", en: "I slept for a long time." },
    ],
    grammarIds: ["gr-a2-01-perfekt"],
    dialogue: [
      { speaker: "Anna", de: "Hallo Ben! Wie war dein Wochenende?", en: "Hi Ben! How was your weekend?" },
      { speaker: "Ben", de: "Sehr schön! Am Samstag habe ich Freunde getroffen.", en: "Very nice! On Saturday I met friends." },
      { speaker: "Anna", de: "Was habt ihr gemacht?", en: "What did you do?" },
      { speaker: "Ben", de: "Wir sind zusammen ins Kino gegangen und haben einen Film gesehen.", en: "We went to the cinema together and watched a film." },
      { speaker: "Anna", de: "Und am Sonntag?", en: "And on Sunday?" },
      { speaker: "Ben", de: "Am Sonntag habe ich lange geschlafen und danach eingekauft.", en: "On Sunday I slept in and then went shopping." },
      { speaker: "Anna", de: "Ich bin zu meinen Eltern gefahren, und meine Mutter hat gekocht.", en: "I went to my parents' place, and my mother cooked." },
      { speaker: "Ben", de: "Schön! Das klingt nach einem guten Wochenende.", en: "Nice! That sounds like a good weekend." },
    ],
    check: [
      {
        prompt: "Gestern ___ ich einen Film gesehen.",
        answer: "habe",
        hint: "Verbs that do not express movement or change of state take this auxiliary, in the ich form.",
      },
      {
        prompt: "Am Sonntag bin ich nach Köln ___.",
        answer: "gefahren",
        hint: "Irregular past participle, placed at the very end of the sentence.",
      },
      {
        prompt: "Wir ___ am Samstag ins Kino gegangen.",
        answer: "sind",
        hint: "Verbs of movement form the Perfekt with the other auxiliary, in the wir form.",
      },
    ],
  },

  // Travel & holidays
  "a2-02-travel-and-holidays": {
    goals: [
      "Say where you travelled and how you got there",
      "Use nach, in die and zum for directions",
      "Book a room and ask for the way",
    ],
    vocab: [
      { de: "Urlaub", en: "holiday, time off", gender: "m" },
      { de: "Reise", en: "trip, journey", gender: "f", plural: "Reisen" },
      { de: "Zug", en: "train", gender: "m", plural: "Züge" },
      { de: "Flug", en: "flight", gender: "m", plural: "Flüge" },
      { de: "Flughafen", en: "airport", gender: "m", plural: "Flughäfen" },
      { de: "Hotel", en: "hotel", gender: "n", plural: "Hotels" },
      { de: "Zimmer", en: "room", gender: "n", plural: "Zimmer" },
      { de: "Koffer", en: "suitcase", gender: "m", plural: "Koffer" },
      { de: "Strand", en: "beach", gender: "m", plural: "Strände" },
      { de: "Fahrkarte", en: "ticket (train, bus)", gender: "f", plural: "Fahrkarten" },
      { de: "buchen", en: "to book" },
      { de: "übernachten", en: "to stay overnight" },
    ],
    phrases: [
      { de: "Im Sommer «fahre ich nach Spanien».", en: "In summer I'm going to Spain." },
      { de: "Nächstes Jahr «fliegen wir in die Schweiz».", en: "Next year we're flying to Switzerland." },
      { de: "Ich möchte «ein Zimmer für zwei Nächte buchen».", en: "I'd like to book a room for two nights." },
      { de: "Letztes Jahr «sind wir an die Nordsee gefahren».", en: "Last year we went to the North Sea." },
      { de: "Wir haben «im Hotel am Strand» übernachtet.", en: "We stayed at the hotel on the beach." },
      { de: "Entschuldigung, wie komme ich «zum Flughafen»?", en: "Excuse me, how do I get to the airport?" },
    ],
    grammarIds: ["gr-a2-04-prepositions", "gr-a2-01-perfekt"],
    dialogue: [
      { speaker: "Lena", de: "Wohin bist du im Urlaub gefahren?", en: "Where did you go on holiday?" },
      { speaker: "Tom", de: "Ich bin nach Italien gefahren.", en: "I went to Italy." },
      { speaker: "Lena", de: "Toll! Wie bist du gereist?", en: "Great! How did you travel?" },
      { speaker: "Tom", de: "Mit dem Zug. Der Flug war mir zu teuer.", en: "By train. The flight was too expensive for me." },
      { speaker: "Lena", de: "Wo hast du übernachtet?", en: "Where did you stay?" },
      { speaker: "Tom", de: "In einem kleinen Hotel am Strand. Das Zimmer war sehr schön.", en: "In a small hotel on the beach. The room was lovely." },
      { speaker: "Lena", de: "Das klingt super. Fährst du nächstes Jahr wieder dorthin?", en: "That sounds great. Will you go there again next year?" },
      { speaker: "Tom", de: "Ja, ich möchte im Sommer wieder nach Italien fahren.", en: "Yes, I'd like to go to Italy again in summer." },
    ],
    check: [
      {
        prompt: "Im Sommer fahren wir ___ Italien.",
        answer: "nach",
        hint: "Which preposition goes with a country or city without an article?",
      },
      {
        prompt: "Das Hotel liegt direkt ___ Meer.",
        answer: "am",
        hint: "Location right next to water: preposition plus dative, contracted with the article.",
      },
      {
        prompt: "Wir haben zwei Nächte in Wien ___.",
        answer: "übernachtet",
        hint: "Perfekt: the participle of this verb stands at the end and has no ge- prefix.",
      },
    ],
  },

  // Health & body (at the doctor)
  "a2-03-health-and-body": {
    goals: [
      "Name body parts and say what hurts",
      "Make a doctor's appointment and describe symptoms",
      "Understand advice with sollen, müssen and the imperative",
    ],
    vocab: [
      { de: "Kopf", en: "head", gender: "m", plural: "Köpfe" },
      { de: "Hals", en: "throat, neck", gender: "m", plural: "Hälse" },
      { de: "Bauch", en: "belly, stomach", gender: "m", plural: "Bäuche" },
      { de: "Rücken", en: "back", gender: "m", plural: "Rücken" },
      { de: "Arzt", en: "doctor (male)", gender: "m", plural: "Ärzte" },
      { de: "Termin", en: "appointment", gender: "m", plural: "Termine" },
      { de: "Fieber", en: "fever", gender: "n" },
      { de: "Husten", en: "cough", gender: "m" },
      { de: "Erkältung", en: "cold", gender: "f", plural: "Erkältungen" },
      { de: "Medikament", en: "medicine", gender: "n", plural: "Medikamente" },
      { de: "Rezept", en: "prescription", gender: "n", plural: "Rezepte" },
    ],
    phrases: [
      { de: "«Mir tut der Kopf weh».", en: "My head hurts." },
      { de: "«Mir geht es nicht gut».", en: "I don't feel well." },
      { de: "Ich möchte «einen Termin vereinbaren».", en: "I'd like to make an appointment." },
      { de: "Sie «müssen viel trinken».", en: "You have to drink a lot." },
      { de: "Du «sollst im Bett bleiben».", en: "You should stay in bed." },
      { de: "«Nehmen Sie die Tabletten dreimal am Tag».", en: "Take the tablets three times a day." },
    ],
    grammarIds: ["gr-a2-03-dative", "gr-a2-07-modal-verbs"],
    dialogue: [
      { speaker: "Markus", de: "Guten Tag. Mir geht es nicht gut.", en: "Good day. I don't feel well." },
      { speaker: "Sabine", de: "Guten Tag. Was fehlt Ihnen denn?", en: "Good day. What seems to be the matter?" },
      { speaker: "Markus", de: "Mir tut der Hals weh, und ich habe Husten.", en: "My throat hurts and I have a cough." },
      { speaker: "Sabine", de: "Haben Sie auch Fieber?", en: "Do you have a fever too?" },
      { speaker: "Markus", de: "Ja, ein bisschen. Seit gestern Abend.", en: "Yes, a little. Since yesterday evening." },
      { speaker: "Sabine", de: "Sie haben eine Erkältung. Sie müssen im Bett bleiben und viel trinken.", en: "You have a cold. You must stay in bed and drink a lot." },
      { speaker: "Markus", de: "Muss ich auch ein Medikament nehmen?", en: "Do I have to take medicine too?" },
      { speaker: "Sabine", de: "Ja, nehmen Sie diese Tabletten zweimal am Tag.", en: "Yes, take these tablets twice a day." },
    ],
    check: [
      {
        prompt: "Mir tut der Rücken ___.",
        answer: "weh",
        hint: "Finish the fixed expression for \"hurts\" that goes with a dative person (mir, dir, ihm).",
      },
      {
        prompt: "Du ___ viel Wasser trinken.",
        answer: "sollst",
        accept: ["musst"],
        hint: "Modal verb for advice or a doctor's recommendation, du form.",
      },
      {
        prompt: "Ich habe Fieber. ___ geht es nicht gut.",
        answer: "Mir",
        hint: "How you feel takes the dative form of ich.",
      },
    ],
  },

  // Weather & seasons
  "a2-04-weather-and-seasons": {
    goals: [
      "Describe the weather with the impersonal es",
      "Say what you do when the weather changes using wenn",
      "Compare the seasons",
    ],
    vocab: [
      { de: "Wetter", en: "weather", gender: "n" },
      { de: "Sonne", en: "sun", gender: "f" },
      { de: "Regen", en: "rain", gender: "m" },
      { de: "Schnee", en: "snow", gender: "m" },
      { de: "Wind", en: "wind", gender: "m", plural: "Winde" },
      { de: "Sommer", en: "summer", gender: "m", plural: "Sommer" },
      { de: "Winter", en: "winter", gender: "m", plural: "Winter" },
      { de: "Jacke", en: "jacket", gender: "f", plural: "Jacken" },
      { de: "Regenschirm", en: "umbrella", gender: "m", plural: "Regenschirme" },
      { de: "regnen", en: "to rain" },
      { de: "schneien", en: "to snow" },
      { de: "kalt", en: "cold" },
    ],
    phrases: [
      { de: "«Es regnet» heute den ganzen Tag.", en: "It's raining all day today." },
      { de: "«Es ist kalt», aber die Sonne scheint.", en: "It's cold, but the sun is shining." },
      { de: "«Wenn es regnet», bleibe ich zu Hause.", en: "When it rains, I stay at home." },
      { de: "«Wenn die Sonne scheint», gehen wir spazieren.", en: "When the sun shines, we go for a walk." },
      { de: "Im Sommer ist es «wärmer als» im Frühling.", en: "In summer it is warmer than in spring." },
      { de: "Im Juli ist es bei uns «am schönsten».", en: "In July it's nicest where we live." },
    ],
    grammarIds: ["gr-a2-05-subordinate-clauses", "gr-a2-06-comparative-superlative"],
    dialogue: [
      { speaker: "Julia", de: "Brr, es ist heute so kalt!", en: "Brr, it's so cold today!" },
      { speaker: "Max", de: "Ja, und es regnet auch. Hast du einen Regenschirm?", en: "Yes, and it's raining too. Do you have an umbrella?" },
      { speaker: "Julia", de: "Nein, aber ich habe eine Jacke. Welche Jahreszeit magst du am liebsten?", en: "No, but I have a jacket. Which season do you like best?" },
      { speaker: "Max", de: "Den Sommer. Im Sommer ist es wärmer als im Frühling.", en: "Summer. In summer it is warmer than in spring." },
      { speaker: "Julia", de: "Ich mag den Winter, wenn es schneit.", en: "I like winter when it snows." },
      { speaker: "Max", de: "Wirklich? Mir ist es im Winter zu kalt.", en: "Really? Winter is too cold for me." },
      { speaker: "Julia", de: "Aber wenn es schneit, ist die Stadt so schön!", en: "But when it snows, the city is so beautiful!" },
      { speaker: "Max", de: "Da hast du recht. Der Schnee ist wirklich schön.", en: "You're right. The snow really is beautiful." },
    ],
    check: [
      {
        prompt: "Immer ___ die Sonne scheint, gehe ich spazieren.",
        answer: "wenn",
        hint: "Conjunction for a repeated situation; the verb moves to the end of the clause.",
      },
      {
        prompt: "Im Sommer ist es viel ___ als im Winter.",
        answer: "wärmer",
        hint: "Comparative of warm: add -er and an umlaut.",
      },
      {
        prompt: "Draußen ist alles weiß: ___ schneit seit gestern.",
        answer: "Es",
        hint: "Weather verbs need a dummy subject pronoun.",
      },
    ],
  },

  // Work & professions
  "a2-05-work-and-professions": {
    goals: [
      "Say what you do for a living and describe your day",
      "Give reasons with weil and dass",
      "Talk about rules and obligations with müssen and dürfen",
    ],
    vocab: [
      { de: "Beruf", en: "profession, job", gender: "m", plural: "Berufe" },
      { de: "Arbeit", en: "work", gender: "f" },
      { de: "Büro", en: "office", gender: "n", plural: "Büros" },
      { de: "Kollege", en: "colleague (male)", gender: "m", plural: "Kollegen" },
      { de: "Kollegin", en: "colleague (female)", gender: "f", plural: "Kolleginnen" },
      { de: "Chef", en: "boss (male)", gender: "m", plural: "Chefs" },
      { de: "Aufgabe", en: "task", gender: "f", plural: "Aufgaben" },
      { de: "Besprechung", en: "meeting", gender: "f", plural: "Besprechungen" },
      { de: "Gehalt", en: "salary", gender: "n", plural: "Gehälter" },
      { de: "Feierabend", en: "end of the working day", gender: "m" },
      { de: "arbeiten", en: "to work" },
      { de: "verdienen", en: "to earn" },
    ],
    phrases: [
      { de: "«Ich arbeite als Ingenieur».", en: "I work as an engineer." },
      { de: "Ich mag meinen Beruf, «weil ich viel Neues lerne».", en: "I like my job because I learn a lot of new things." },
      { de: "Ich finde es gut, «dass meine Kollegen nett sind».", en: "I like that my colleagues are nice." },
      { de: "Ich «muss um acht Uhr im Büro sein».", en: "I have to be at the office at eight." },
      { de: "In der Besprechung «dürfen wir unser Handy nicht benutzen».", en: "In the meeting we are not allowed to use our phones." },
      { de: "Um fünf Uhr «habe ich Feierabend».", en: "At five o'clock I finish work." },
    ],
    grammarIds: ["gr-a2-05-subordinate-clauses", "gr-a2-07-modal-verbs"],
    dialogue: [
      { speaker: "Nina", de: "Was machst du beruflich, Paul?", en: "What do you do for a living, Paul?" },
      { speaker: "Paul", de: "Ich arbeite als Lehrer. Und du?", en: "I work as a teacher. And you?" },
      { speaker: "Nina", de: "Ich bin Softwareentwicklerin. Ich arbeite gern, weil meine Kollegen so nett sind.", en: "I'm a software developer. I like working because my colleagues are so nice." },
      { speaker: "Paul", de: "Das ist wichtig. Ich finde es gut, dass ich viel mit Kindern arbeite.", en: "That's important. I like that I work with children a lot." },
      { speaker: "Nina", de: "Musst du früh anfangen?", en: "Do you have to start early?" },
      { speaker: "Paul", de: "Ja, ich muss um sieben Uhr in der Schule sein.", en: "Yes, I have to be at school at seven." },
      { speaker: "Nina", de: "Oh, das ist früh! Ich darf zweimal pro Woche zu Hause arbeiten.", en: "Oh, that's early! I'm allowed to work from home twice a week." },
      { speaker: "Paul", de: "Das ist toll! Dann musst du morgens nicht so früh aufstehen.", en: "That's great! Then you don't have to get up so early in the morning." },
    ],
    check: [
      {
        prompt: "Ich mag meinen Job, ___ ich nette Kollegen habe.",
        answer: "weil",
        accept: ["da"],
        hint: "Conjunction giving a reason; the conjugated verb goes to the end.",
      },
      {
        prompt: "Ich finde es gut, dass ich um fünf Uhr Feierabend ___.",
        answer: "habe",
        hint: "In a dass-clause the conjugated verb comes last; use the ich form.",
      },
      {
        prompt: "Hier ist es verboten: Wir ___ im Büro nicht rauchen.",
        answer: "dürfen",
        hint: "Modal verb for permission and prohibition, wir form.",
      },
    ],
  },

  // Living & rooms
  "a2-06-living-and-rooms": {
    goals: [
      "Name the rooms and the furniture in your home",
      "Say where things are with in, an, auf and the dative",
      "Use stehen, liegen and hängen correctly",
    ],
    vocab: [
      { de: "Küche", en: "kitchen", gender: "f", plural: "Küchen" },
      { de: "Wohnzimmer", en: "living room", gender: "n", plural: "Wohnzimmer" },
      { de: "Schlafzimmer", en: "bedroom", gender: "n", plural: "Schlafzimmer" },
      { de: "Badezimmer", en: "bathroom", gender: "n", plural: "Badezimmer" },
      { de: "Tisch", en: "table", gender: "m", plural: "Tische" },
      { de: "Stuhl", en: "chair", gender: "m", plural: "Stühle" },
      { de: "Sofa", en: "sofa", gender: "n", plural: "Sofas" },
      { de: "Bett", en: "bed", gender: "n", plural: "Betten" },
      { de: "Regal", en: "shelf", gender: "n", plural: "Regale" },
      { de: "Lampe", en: "lamp", gender: "f", plural: "Lampen" },
      { de: "Wand", en: "wall", gender: "f", plural: "Wände" },
      { de: "Miete", en: "rent", gender: "f", plural: "Mieten" },
    ],
    phrases: [
      { de: "«In der Küche» steht ein runder Tisch.", en: "In the kitchen there is a round table." },
      { de: "Das Buch «liegt auf dem Tisch».", en: "The book is lying on the table." },
      { de: "Das Bild «hängt an der Wand».", en: "The picture is hanging on the wall." },
      { de: "«Im Wohnzimmer» steht ein großes Sofa.", en: "In the living room there is a big sofa." },
      { de: "Das Regal steht «neben dem Bett».", en: "The shelf is next to the bed." },
      { de: "Wir bezahlen «600 Euro Miete» im Monat.", en: "We pay 600 euros rent a month." },
    ],
    grammarIds: ["gr-a2-04-prepositions", "gr-a2-03-dative"],
    dialogue: [
      { speaker: "Tim", de: "Wie gefällt dir deine neue Wohnung, Eva?", en: "How do you like your new flat, Eva?" },
      { speaker: "Eva", de: "Sehr gut! Sie hat zwei Zimmer und eine kleine Küche.", en: "Very much! It has two rooms and a small kitchen." },
      { speaker: "Tim", de: "Und wie sieht das Wohnzimmer aus?", en: "And what does the living room look like?" },
      { speaker: "Eva", de: "Das Sofa steht am Fenster, und der Tisch steht vor dem Sofa.", en: "The sofa is by the window, and the table is in front of the sofa." },
      { speaker: "Tim", de: "Hast du auch ein Bild?", en: "Do you have a picture too?" },
      { speaker: "Eva", de: "Ja, das Bild hängt über dem Sofa.", en: "Yes, the picture hangs above the sofa." },
      { speaker: "Tim", de: "Und wie viel Miete bezahlst du?", en: "And how much rent do you pay?" },
      { speaker: "Eva", de: "Nur 600 Euro im Monat. Im Schlafzimmer steht mein Bett, mehr nicht.", en: "Only 600 euros a month. In the bedroom there is my bed, nothing more." },
    ],
    check: [
      {
        prompt: "Das Buch liegt auf ___ Tisch.",
        answer: "dem",
        hint: "Position (where?) takes the dative; Tisch is masculine.",
      },
      {
        prompt: "Die Lampe hängt an ___ Wand.",
        answer: "der",
        hint: "Position (where?) takes the dative; Wand is feminine.",
      },
      {
        prompt: "Im Schlafzimmer ___ ein Bett.",
        answer: "steht",
        hint: "Position verb for furniture that is upright on its legs.",
      },
    ],
  },

  // Invitations & appointments
  "a2-07-invitations-and-appointments": {
    goals: [
      "Invite someone and suggest a time",
      "Accept an invitation or politely turn it down",
      "Use können and wollen in everyday arrangements",
    ],
    vocab: [
      { de: "Einladung", en: "invitation", gender: "f", plural: "Einladungen" },
      { de: "Geburtstag", en: "birthday", gender: "m", plural: "Geburtstage" },
      { de: "Party", en: "party", gender: "f", plural: "Partys" },
      { de: "Kino", en: "cinema", gender: "n", plural: "Kinos" },
      { de: "Vorschlag", en: "suggestion", gender: "m", plural: "Vorschläge" },
      { de: "Zeit", en: "time", gender: "f" },
      { de: "Lust", en: "desire, feeling like doing something", gender: "f" },
      { de: "einladen", en: "to invite" },
      { de: "zusagen", en: "to accept (an invitation)" },
      { de: "absagen", en: "to decline, to cancel" },
      { de: "vorschlagen", en: "to suggest" },
      { de: "vorbeikommen", en: "to drop by" },
    ],
    phrases: [
      { de: "«Hast du am Samstag Zeit»?", en: "Do you have time on Saturday?" },
      { de: "«Hättest du Lust auf» einen Film?", en: "Would you like to see a film?" },
      { de: "«Ich möchte dich zu meiner Party einladen».", en: "I'd like to invite you to my party." },
      { de: "«Ich kann leider nicht», ich muss arbeiten.", en: "I'm afraid I can't, I have to work." },
      { de: "«Wollen wir uns um sieben Uhr treffen»?", en: "Shall we meet at seven o'clock?" },
      { de: "«Wie wäre es mit» Freitag?", en: "How about Friday?" },
    ],
    grammarIds: ["gr-a2-07-modal-verbs"],
    dialogue: [
      { speaker: "Sara", de: "Hallo Jan! Hast du am Samstag Zeit?", en: "Hi Jan! Do you have time on Saturday?" },
      { speaker: "Jan", de: "Ja, ich glaube schon. Was hast du vor?", en: "Yes, I think so. What are you planning?" },
      { speaker: "Sara", de: "Ich möchte dich zu meinem Geburtstag einladen.", en: "I'd like to invite you to my birthday." },
      { speaker: "Jan", de: "Gern! Wann fängt die Party an?", en: "Gladly! When does the party start?" },
      { speaker: "Sara", de: "Um acht Uhr. Wollen wir uns vorher treffen?", en: "At eight. Shall we meet beforehand?" },
      { speaker: "Jan", de: "Leider kann ich nicht früher kommen, ich muss bis sieben arbeiten. Aber ich kann um acht da sein.", en: "Unfortunately I can't come earlier, I have to work until seven. But I can be there at eight." },
      { speaker: "Sara", de: "Kein Problem! Dann sehen wir uns am Samstag.", en: "No problem! Then we'll see each other on Saturday." },
      { speaker: "Jan", de: "Super, ich freue mich! Vielen Dank für die Einladung.", en: "Great, I'm looking forward to it! Thanks for the invitation." },
    ],
    check: [
      {
        prompt: "Ich ___ am Samstag leider nicht kommen, ich habe keine Zeit.",
        answer: "kann",
        hint: "Modal verb for ability or possibility, ich form.",
      },
      {
        prompt: "___ wir uns um sieben Uhr treffen?",
        answer: "Wollen",
        accept: ["Sollen"],
        hint: "Modal verb that starts a question making a suggestion, wir form.",
      },
      {
        prompt: "Ich möchte dich zu meinem Geburtstag ___.",
        answer: "einladen",
        hint: "After möchte, the separable verb stays in one piece at the end.",
      },
    ],
  },

  // Comparing things
  "a2-08-comparing-things": {
    goals: [
      "Compare two things with the comparative and als",
      "Say that two things are equal with so … wie",
      "Name the best or most with the superlative and justify a choice",
    ],
    vocab: [
      { de: "Stadt", en: "city, town", gender: "f", plural: "Städte" },
      { de: "Preis", en: "price", gender: "m", plural: "Preise" },
      { de: "Unterschied", en: "difference", gender: "m", plural: "Unterschiede" },
      { de: "Verkehrsmittel", en: "means of transport", gender: "n", plural: "Verkehrsmittel" },
      { de: "Fahrrad", en: "bicycle", gender: "n", plural: "Fahrräder" },
      { de: "Auto", en: "car", gender: "n", plural: "Autos" },
      { de: "schnell", en: "fast" },
      { de: "billig", en: "cheap" },
      { de: "teuer", en: "expensive" },
      { de: "bequem", en: "comfortable" },
      { de: "gut", en: "good" },
    ],
    phrases: [
      { de: "Berlin ist «größer als» Hamburg.", en: "Berlin is bigger than Hamburg." },
      { de: "Das Fahrrad ist in der Stadt «so schnell wie» das Auto.", en: "In the city the bike is as fast as the car." },
      { de: "Ich finde den Zug «am bequemsten».", en: "I find the train the most comfortable." },
      { de: "Mein Bruder kocht «besser als» ich.", en: "My brother cooks better than I do." },
      { de: "Hier ist es «nicht so teuer wie» in München.", en: "It's not as expensive here as in Munich." },
      { de: "Ich fahre «lieber mit dem Zug als mit dem Auto».", en: "I prefer to travel by train rather than by car." },
    ],
    grammarIds: ["gr-a2-06-comparative-superlative"],
    dialogue: [
      { speaker: "Lisa", de: "Felix, wohnst du lieber in der Stadt oder auf dem Land?", en: "Felix, do you prefer living in the city or in the country?" },
      { speaker: "Felix", de: "In der Stadt. Sie ist größer, und es gibt mehr Kinos.", en: "In the city. It's bigger and there are more cinemas." },
      { speaker: "Lisa", de: "Aber die Wohnungen sind teurer als auf dem Land.", en: "But flats are more expensive than in the country." },
      { speaker: "Felix", de: "Stimmt. Dafür fahre ich nur mit dem Fahrrad, das ist billiger als ein Auto.", en: "True. On the other hand I only ride my bike, which is cheaper than a car." },
      { speaker: "Lisa", de: "Ist das Fahrrad auch so schnell wie das Auto?", en: "Is the bike as fast as the car too?" },
      { speaker: "Felix", de: "In der Stadt ja, oft sogar schneller!", en: "In the city yes, often even faster!" },
      { speaker: "Lisa", de: "Ich fahre trotzdem am liebsten mit dem Zug. Er ist am bequemsten.", en: "I still like going by train best. It's the most comfortable." },
      { speaker: "Felix", de: "Da hast du recht. Aber das Fahrrad ist am gesündesten.", en: "You're right. But the bike is the healthiest." },
    ],
    check: [
      {
        prompt: "Berlin ist viel ___ als meine Stadt.",
        answer: "größer",
        hint: "Comparative of groß: add -er and an umlaut.",
      },
      {
        prompt: "Das Fahrrad ist so schnell ___ das Auto.",
        answer: "wie",
        hint: "After so + adjective, use the word for equality, not als.",
      },
      {
        prompt: "Mein Bruder kocht ___ als ich.",
        answer: "besser",
        hint: "Irregular comparative of gut.",
      },
    ],
  },
};
